'use client'
import { useState, useContext } from 'react';
import signUp from '@/firebase/auth/signup';
import { DataContext } from '@/context/DataContext';
import { generatePDF } from '@/utils/pdfUtils';

const listaDefensa = `DR. ABARCA GOMEZ MARCELO ANTONIO
DRA. ABELLAN SILVINA
DRA. ADARVEZ NATALIA
DR. ADARVEZ OSCAR
DR. AGRELLO FRANCISCO JOSE
DRA. AGUERO CARLA MARIA
DRA. AGUERO ERICA VICTORIA
DR. AGUIAR JULIAN ERNESTO
DR. AGUIAR FEDERICO
DRA. AGUILERA MARIA ROCIO
DRA. AGUILERA NOELIA DEL CARMEN
DR. AGUIAR JORGE
DRA. AGUIRRE CELIA MABEL
DR. AGUIRRE FERNANDO
DR. AGUIRRE RODRIGO JOSE
DRA. AHUMADA IVANA MARIELA
DRA. ALANIS SABAG SANDRA VIVIANA
DRA. ALARCON CAPDEVILA ESTEFANIA PAMELA
DR. ALCALA PABLO ANDRES
DRA. ALCAYAGA ZALAZAR GRENDA VALENTINA
DR. ALE RODRIGO
DRA. ALLENDE FLAVIA GABRIELA
DRA. ALMAZAN MARIA SOLEDAD
DRA. ALTAMIRA GALEONE MARIA LAURA DEOLINDA
DR. ALVAREZ JUAN ANTONIO
DR. AMANTE CARLA
DR. AMARFIL JORGE
DR. AMAYA DARIO
DR. AMAYA GERMAN ROGER
DR. ANDINO JOSE
DR. ANDINO MAXIMILIANO MANUEL
DRA. ANZOR AMIRA CELESTE
DR. ARACENA RICARDO
DR. ARACENA RUZYCKI JOSE MARIA
DR. ARANCIBIA MARCELO
DRA. ARANDA NATALIA
DR. ARCE BROZINA CRISTINA
DR. ARCENIO YORDAN DEMETRIO
DRA. ARIAS ANA LAURA
DRA. ARIAS ANA MARIA
DRA. ARIAS NELIDA RUBI
DRA. ARIAS VILLARROEL YESICA EVELIN
DR. ARMADA CAMPOS MAXIMILIANO
DR. ARNAU GUSTAVO MARTIN
DRA. ARROYO ANA CAROLINA
DR. ARROYO FACUNDO
DRA. ASTORGA ALEJANDRA
DR. ATENCIO ELBA
DRA. AVELEDO NATALIA
DR. AVILA GUSTAVO RICARDO
DR. AVILA PABLO
DRA. BAIGORRIA EMA
DR. BALDERRAMO ANDRES OMAR
DR. BALMACEDA BENJAMIN
DR. BALMACEDA QUIROGA DANIEL
DRA. BALMACEDA MIRNA ALEJANDRA
DR. BARAGAÑO CRISTIAN
DR. BARBERO CORREA ALEKANDRA
DR. BARRERA PABLO
DR. BARRIONUEVO MARCIAL EDUARDO
DRA. BARROS LORENA LARA
DRA. BASSO BERNAL PATRICIA
DR. BAZAN LEANDRO
DR. BECERRA MIGUEL ANGEL
DR. BECERRA PONCE JOSE ALBERTO
DR. BEDINI REINALDO LUCIANO
DR. BELBRUNO JUAN ANGEL
DRA. BELEN VIVIANA
DR. BELTRAN JOSE MANUEL
DR. BENAVIDEZ LUCIO
DR. BENITEZ HERNAN RAMIRO
DR. BERRIDO ROLANDO
DR. BERTAGNA ANDRES
DRA. BIANCHI CECILIA
DR. BODE ARTURO
DR. BOGNI MAGGIO JUAN ANTONIO
DR. BONOMO ENZO
DR. BONOMO FERNANDO
DR. BRAVO ALEJANDRO
DR. BRIZUELA PAEZ NESTOR
DR. BUENO FERNANDO
DR. BURGOS DANIEL
DRA. BURGUEZ MARIA ENCARNACION
DR. BUSTOS CARGIA MARIO ARIEL
DR. BUSTOS GERARDO
DR. BUSTOS LASPINA RAUL FERNANDO
DRA. CABALLERO ACHEM MARIA LEILA
DRA. CABRERA DE PANDIELLA ADRIANA
DRA. CACERES BRENDA
DR. CACERES EDUARDO
DRA. CACERES MONICA
DRA. CAMARGO MARIA DELIA
DRA. CAMPILLAY JULIETA
DRA. CAMPILLAY SABRINA
DRA. CAMPORA GUTIERREZ FLAVIA LORENA
DR. CAMPORA GUTIERREZ ARNALDO ABEL
DR. CAMPORA JUAN JAVIER
DRA. CAMPOS SEGURA YANINA
DR. CANO GUILLERMO
DRA. CANTEROS ALEJANDRA
DR. CAPARROS DARIO
DRA. CARMONA ANA SOFIA
DR. CARRIZO CESAR
DR. CARRIZO GUILLERMO JESUS
DRA. CARRIZO GISELLE ALICIA
DR. CARRIZO HORACIO NICOLAS
DR. CARRIZO JOSE NICOLAS
DRA. CARRIZO LAURA NATALIA
DRA. CARRIZO MARIA JOSE
DRA. CARRIZO PATRICIA ALEJANDRA
DR. CASTAN ALEJANDRO
DR. CASTAN JORGE
DRA. CASTRO CARINA
DR. CASTRO FERNANDO
DR. CASTRO JOSE LUIS
DR. CHAVEZ FERNANDO
DR. CONTURSO JORGE IGNACIO
DR. CONTURSO FAVIO
DR. CORDIGLIA NICOLAS
DR. CORIA JORGE ANDRES
DRA. CORIA MARIANA ANTONELA
DR. CORIA MARIEL CARLOS MANUEL
DAR. CORREA CAROLINA
DR. CORREA EDGARDO MIGUEL
DR. CORREA ESBRY ROBERTO LUIS
DR. CORREA SANCHEZ MARCELO SEBASTIAN
DR. CORTEZ SERGIO ANDRES
DR. CORTEZ SORIA JAVIER AGUSTIN
DR. CORTIGLIA NICOLAS
DRA. COZZI SANDRA ELIZABETH
DR. CRIFO JORGE
DR. CUELLO MAXIMILIANO
DR. CULKAJ IVAN
DRA. CULKAJ MORA CECILIA ELIZABETH
DR. DAMICO QUINTAR GABRIEL ANTONIO
DR. DAMICO RAUL ALEJANDRO
DR. DAVILA ALEJANDRO CARLOS
DRA. DE DAX SANSO MARIA VANESA
DR. DE LA FUENTE GUSTAVO
DRA. DE LA PORTE FLORENCIA
DRA. DE LA TORRE ANA
DR. DE LA TORRE ANTONIO
DRA. DE LA VEGA MARCELA
DR. DE ORO HUGO
DR. DE PANE SANCHEZ FRANCISCO PABLO
DR. DE VITA JOSE MARIA
DRA. DELGADO GRACIELA
DRA. DERKA NADIA LUDMILA
DRA. DIAS MARIA JOSE
DRA. DIAZ FIOR CARLA
DR. DIAZ LOPEZ MATIAS
DR. DIAZ PATRICIO
DRA. AVIAR DORITA 
DR. DRAGANI ZARRACAN SANTIAGO EZEQUIEL
DR. DUANO GUILLERMO
DR. DURAN HERNANDEZ NESTOR REINALDO
DR. ECHEGARAY FERNANDO
DRA. ECHEGARAY MOYA JOSELA
DRA. ECHEGARAY PAULA
DRA. ECHEVARRIA MANRIQUE MARIA MICAELA
DRA. EGUREN LUCIANA
DRA. ELIAS MAIRA
DR. ELIZONDO FERNANDO
DR. ELIZONDO JULIO HORACIO
DR. ESCUDERO MAURICIO FABIAN
DR. ESCUDERO LUIS
DRA. ESCUDERO PAOLA
DR. ESPEJO ADRIAN
DR. ESPEJO AMARFIL ESTEBAN ADRIAN
DR. ESPEJO CESAR ANDRES
DR. ESPINOSA MATIAS
DR. ESPINOSA RAMIRO
DRA. ESPINOZA MARGARITA
DRA. ESQUIVEL ANALIA GEMA
DR. ESQUIVEL JORGE JOSE
DRA. ESTEVEZ LUCIANA
DR. FACHINETTI FABRICIO
DR. FALCON ANTONIO
DRA. FALCON SILVIA MABEL
DRA. FALIVENE GISELA
DRA. FERNANDEZ ESTEFANIA
DR. FERNANDEZ HIPOLITO
DR. FERNANDEZ MARCELO
DR. FERNANDEZ TORRES CARLOS
DR. FERNANDEZ VICENTE RAUL
DRA. FERRANDIZ ANA MARIANA
DR. FERRE CRISTIAN ARIEL
DR. FIORENTINO NICOLAS
DRA. FLORES CLAUDIA NOEMI
DR. FLORES EUGENIO EDUARDO
DR. FLORES ICAZZATTI
DR. FLORES MARCELO
DRA. FLORES YANINA PAOLA
DR. FLOREZ ICAZZATTI
DR. FONZALIDA JUAN HUMBERTO
DRA. FORTE EMILCE
DRA. FUNES FLAVIA BELEN
DR. FURLOTTI ANGEL HUMBERTO RAMON
DR. FURLOTTI FRANCISCO RICARDO
DR. GALAN JOSE LUIS
DRA. GALINDEZ JORGELINA
DR. GALLO MARIO
DRA. GALLO PAGES MARIA PAULA
DR. GALVARINI LUIS FEDERICO
DRA. GALVEZ GABRIELA ELINA
DRA. GAMBOA COSTA SOFIA INES
DR. GANGEMI, GUIDO JORDAN
DR. GARCIA ALVAREZ LUIS LEONEL
DR. GARCIA CASTRILLON JOSE LUIS
DR. GARCIA GUILLEN RODRIGO ENRIQUE
DR. GARCIA GUILLEN RODRIGO SAMUEL
DRA. GARCIA GUTIERREZ SILVIA
DRA. GARCIA GUZMAN ANA LAURA
DRA. GARCIA LEGUIZA ANDREA LORENA
DR. GARCIA LUCIO NESTOR
DR. GARCIA PACHECO JUAN
DR. GARCIA SANTIAGO
DR. GARCIA MILENCO
DRA. GARCIA VERONICA
DR. GARRIDO BALMACEDA GASTON OMAR
DR. GATICA AGUSTIN
DR. GELVEZ FAUSTINO
DR. GELVEZ MUÑOZ MIGUEL ANGEL
DR. GENEST ALEJANDRO
DRA. GENNARO SILVANA ELIZABETH
DR. GIACCAGLI GUSTAVO DANIEL
DRA. GIANINETTO CAROLINA
DR. GIL GASTON ALBERTO
DR. GIL JULIAN
DR. GIL, GASTON ALBERTO
DR. GIMENES PUCHOL, MANUEL
DRA. GIMENEZ SABRINA
DR. GIZZI JOSE
DR. GIZZI JUAN CARLOS
DR. GODOY CASTRO NARCISO JESUS
DR. GOMEZ CAMOZZI NICOLAS
DR. GOMEZ DIEGO EDUARDO
DR. GOMEZ DUILIO
DR. GOMEZ EDGARDO
DRA. GOMEZ JOFRE JESICA LORENA
DRA. GOMEZ MARIELA
DR. GOMEZ SERGIO
DRA. GOMEZ DIAZ ERICA
DR. GONZALEZ AGUILERA GUSTAVO ARIEL
DRA. GONZALEZ GABRIELA
DRA. GONZALEZ GABRIEL EDUARDO
DR. GONZALEZ GUSTAVO
DR. GONZALEZ JUAN CARLOS
DRA. GONZALEZ LIZZI NATACHA
DRA. GONZALEZ MONICA
DR. GONZALEZ NICOLAS ERNESTO
DR. GONZALEZ VIOLA FEDERICO
DRA. GONZALEZ YANINA
DRA. GRCIC KARLA
DRA. GRECO SAAD NATALIA
DRA. GROSSO NATALIA
DRA. GUARDIA LILIANA
DRA. GUARDIA MIRTA ROSA
DR. GUERRERO FERNANDO
DRA. GUERRERO MARIA VICTORIA
DRA. GUEVARA NATALIA
DR. GUIDET MONTILLA JOSE LUIS
DR. GUILLEN GIMENEZ JORGE ENRIQUE
DR. GUIRADO FACUNDO
DR. GYORDAN ROSA ARSENIO DEMETRIO
DRA. GUTIERREZ SANDRA
DRA. GUZMAN MARIA GUADALUPE
DRA. GUZMAN VEGA PATRICIA ANDREA
DRA. HEREDIA ESTEFANIA NATALIA
DR. HERRERO MATIAS GABRIEL
DR. HERRERO PALACIOS JOSE MANUEL
DR. HERMAN AMIN LUCAS
DR. HERRMANN SERRA JORGE THEODORO
DR. HIDALGO ALEJANDRO DANIEL
DR. HIDALGO ISMAEL ANTONIO
DR. HIDALGO RAFAEL
DRA. IBAÑEZ ANA PAULA
DRA. IBAÑEZ PAOLA
DRA. IDEMI AGUSTIN
DR. ILLANES CABALLERO MARÍA BELÉN 
DR. ILLANES ROBERTO ARIEL
DRA. ILLANES MARIA GUADALUPE
DRA. ILLANEZ MARISEL
DR. IMPARADO PABLO
DRA. IRAGORRE ESTER
DR. ITURRIETA DIEGO
DR. JAIME OVALLES DANIEL
DR. JOFRE ANTONIO JAVIER
DRA. JOFRE JESICA
DR. JOFRE, CESAR ROLANDO
DRA. JORDA MEDINA ROSA ANTONIA
DRA. JORQUERA VALERIA
DR. JUAREZ GUIDO
DR. JUAREZ JUAN CARLOS
DR. JUNES NAVAS CRISTIAN
DR. JURI ALBARRACIN AILEN
DR. KERMAN ERNESTO
DRA. KOSS ALEJANDRA
DR. LACIAR DANIEL
DRA. LAHOZ GRISELDA ESTHER
DR. LARA JESUS GUILLERMO
DRA. LARA LORENA
DR. LAVIA PAEZ JOSE LUIS
DRA. LEITES MALDONADO GABRIELA
DR. LEON PABLO
DR. LEONARDI GUILLERMO
DRA. LEVEQUE SANDRA LORENA
DRA. LIMOLE YANINA DEOLINDA
DR. LISANDRELLO DANIEL
DR. LIVIA PAEZ JOSE LUIS
DR. LLORCA RAUL REINALDO
DR. LLOVERAS ERNESTO OMAR
DRA. LLOVERAS MARIA CECILIA
DR. LLOVERAS PARRA RUBEN EDUARDO
DR. LLOVERAS WALTER ALBERTO
DR. LOPEZ HEREDIA GONZALO ADRIAN
DRA. LOPEZ JULIANA
DR. LOPEZ MARTI ADOLFO ENRIQUE
DR. LOPEZ MARTI SERGIO
DR. LOPEZ RENATO RAMIRO
DR. LORENTE DANIEL
DR. LORENZO MIRA RICARDO DAVID
DR. LOYOLA OMAR
DR. LUCERO SOSA NICOLAS IVAN
DR. LUNA MARIO ALDREDO
DRA. MALDONADO ANALIA CECILIA
DRA. MANCINI SILVIA
DRA. MANINI CORTEZ CARLA MARCELA
DR. MANZUR PABLO
DR. MALDONADO DANIEL
DR. MARCHESE FRANCO
DR. MARCHESI CRISTIAN ALEJANDRO
DR. MARCOS PAZ MAXIMILIANO
DR. MARINARO JUAN MANUEL
DRA. MARQUEZ YANINA
DR. MARTIN CLAVEL GUSTAVO FABIAN
DR. MARTIN IVAN
DRA. MARTIN SILVANA
DR. MARTINEZ CARINA
DR. MARTINEZ ORO HUMBERTO
DRA. MARTINEZ YANINA
DR. MASSA MATIAS
DRA. MATONS MARIA LUISA
DR. MAZZEI MATTAR SANTIAGO ABEL
DRA. MEDINA GABRIELA FERNANDA DEL PILAR
DR. MELIAN NAVARRO JUAN PABLO
DR. MERINO HORACIO
DR. METOLA SAN NICOLAS RODRIGO DANIEL
DRA. MEYER ESPIN ANA CAROLINA
DRA. MIERS PAOLA
DR. MIGANI ELMO
DR. MIODOWSKY ENRIQUE
DR. MIQUELARENA MERITELO ALEJANDRO DANIEL
DR. MIRANDA GUIDET JULIO ADRIAN
DR. MIRANDA MAXIMILIANO ANDRES
DR. MIRANDA LEONARDO ISAIAS
DR. MIRANDA MIGUEL ANGEL
DR. MOINE GALDEANO JOAQUIN
DRA. MOLINA JAIME MARIA ELENA
DR. MOLINA MEGLIOLI DIEGO RAUL
DR. MOLINA PERZI FERNANDO
DR. MOLINERO FEDERICO JESUS
DR. MONCUNILL CARLOS CESAR
DRA. MONDINO LOPEZ FIORELLA
DRA. MONSALVO ENCARNACIÓN
DR. MONTAÑA EZEQUIEL ANDRES
DR. MONTAÑO ROLANDO LORENZO
DR. MONTES FRANCO JOSE
DRA. MONTES BUSTOS MARIA VICTORIA
DRA. MONTILLA MARIA INES
DR. MONTILLA ROBERTO JORGE
DR. MONTIVERO OSVALDO ELIAS
DR. MONTIVERO OSVALDO NICOLAS
DR. MONTIVERO PALACIO GERMAN ANTONIO
DRA. MONTIVERO VALERIA
DRA. MONTIVEROS ROMINA
DR. MORA ANTONIO
DR. MORENO LEANDRO
DR. MORAN MARIO DAVID
DR. MOREIRA FERNANDO
DRA. MORENO CAROLINA
DR. MORENO ROJAS RAUL ENRIQUE
DR. MOYANO EMILIO
DR. MULLEADY LUIS
DR. MUÑOZ CABRAL MAXIMILIANO ANDRES
DRA. MUÑOZ VANINA
DR. MUT CEREZO, MARCELO
DR. NACUSSI PABLO
DRA. NAVEDA MARIA CRISTINA
DRA. NEBREDA LORENA
DRA. NICOLIA SOLEDAD
DRA. NIEVAS DANIELA
DR. NOGUERA ANDRES ALEJANDRO
DR. NOGUERA JULIO CESAR
DRA. NORIEGA MARIA FILOMENA
DR. NOVARO RAMIRO
DRA. NUÑEZ JUANA ISABEL
DRA. NUÑEZ LAURA
DRA. NUÑEZ MARIANA
DR. NUÑEZ MAURICIO
DR. OCAMPO JIMENEZ MARIO FERNANDO
DR. OKI BONANNO, CINTIA
DR. OLIVER MONTILLA ALEJANDRO ALFREDO
DR. OLIVERA LEGLEU JORGE ANTONIO
DRA. OLIVERA SOLER MARIA DE LOS ANGELES
DR. OLIVERA NESTOR MANUEL
DR. OLIVERA ROBERTO CARLOS
DR. OLIVERA SANCHEZ FABIAN RODOLFO
DRA. OLMOS BUSTOS YANINA NATALIA
DRA. OLMOS MOROZ MARCELA FABIANA
DRA. ORELLANO CRISTINA ESTER
DRA. ORELLANO GRAMAJO GEMMA TRINIDAD
DR. OROPEL NICOLAS
DR. OROZCO MAXIMILIANO GUSTAVO
DR. ORTIZ MAXIMILIANO
DR. OTTOLIA CAPUTO ARNALDO DANIEL
DR. OVIEDO ROBERTO ANDRES
DRA. PABON SILVIA
DR. PACHECO ANDRES MAURICIO
DR. PADILLA EDUARDO JOSE
DR. PADILLA RUZ MARIO JAVIER
DR. PAEZ DELGADO MAXIMILIANO
DRA. PAEZ JESICA
DR. PAGES JUAN JOSE
DRA. PAINEVILU CRISTINA VANESA
DR. PALACIOS GONZALO
DRA. PALACIOS MARISA
DR. PALUMBO GASTON
DRA. PANDIELLA ADRIANA
DRA. PANDIELLA FERNANDA EMILSE
DRA. PAREDES VALERIA IVANA
DR. PASCUAL HERNAN
DRA. PAVON VILLALA DENISE YESICA
DRA. PAZ SUSANA VANESA
DRA. PELAYTAY PATRICIA
DR. PELUC PEREZ SEBASTIAN
DR. PENIZZOTO CRISTIAN
DR. PENIZZOTTO ENZO
DR. PEÑA ANGEL DANIEL
DR. PERALTA HENRI
DR. PEREIRA SAMPER PABLO MARCELO
DRA. PEREYRA MARIA VALERIA
DR. PEREYRA PABLO MARCELO
DR. PEREZ SERGIO
DRA. PEREZ OLGA MARIELA
DRA. PERSIA ANA INES
DR. PERZI LEONARDO RAUL
DR. PESQUERA JORGE RAFAEL
DR. PETRIGNANI FEDERICO
DRA. PIOZZI YAMILA
DR. POBLETE JUAN EDUARDO
DRA. POBLETE PATRICIA
DR. PONCE HECTOR
DR. PONCE JUAN
DR. PONTORIERO RUBEN ALFREDO
DR. PONTORIERO SEBASTIAN
DR. PORTELL MAURICIO
DR. PORTILLO PABLO
DR. PORTO MARADONA CESAR AUGUSTO
DR. POSLEMAN EDUARDO
DR. POTELL MAURICIO
DR. PRADO GARCIA EMILIANO ANGEL
DRA. PUTELLI DELGADO MARIA AGUSTINA
DR. QUERO RENZO
DR. QUIROGA BUBICA FRANCISCO JESUS
DR. QUIROGA ENRIQUE PASCUAL
DR. QUIROGA OMAR
DR. QUIROGA TORRES CARLOS ALBERTO
DR. QUIROGA VARGAS OMAR NESTOR
DRA. QUIROGA DE ZALAZAR ELENA BEATRIZ
DRA. RAMIREZ ELIANA
DR. RAMOS GUTIERREZ JORGE ALBERTO
DR. RAMPULLA PABLO
DRA. REBOREDO NELIDA ADRIANA
DRA. RECABARREN ZAMARBIDE VALERIA AIDA
DR. REINOSO CARLOS ALBERTO
DR. REINOSO CARLOS ROBERTO
DRA. REUS LAURA
DRA. REYNOSO GABRIELA
DRA. RICCHINI SILVINA
DRA. RIOS MARIA MABEL
DR. RIVADEO CARLOS DANIEL
DR. RIVAS QUIROGA GUSTAVO ESTEBAN
DR. RIVERA FERNANDO
DR. RIVERAS QUIROGA GUSTAVO ESTEBAN
DR. RIVERO JOSE ALEJANDRO
DRA. RIVEROS DANIELA
DR. RIVEROS JUAN MANUEL
DR. RIVEROS JOSE
DR. RIVEROS LUIS ARIEL
DRA. ROBLES ROCA ANA MARIA
DR. ROCO ALBERTO
DR. ROCO VARELA ELIO
DRA. RODRIGUEZ ANDREA
DR. RODRIGUEZ MUÑOZ MIGUEL ANTONIO
DR. RODRIGUEZ CLAUDIO
DR. RODRIGUEZ JAVIER
DR. ROJAS ANIBAL
DR. ROJAS ELENA NELIDA
DR. ROJAS GONZALO MARTIN
DR. ROJO RAUL
DR. ROMAN BARON LIDIA ANDREA
DR. ROMAN IVAN
DR. ROMAN JAVIER
DR. ROMERO DANIEL
DR. ROMERO VERA DARIO JAVIER
DR. RUBIÑO DANIEL ALEJANDRO
DRA. RUBY NELIDA
DR. RUEDA CARLOS ANDRES
DR. RUIZ CARLOS ALBERTO
DRA. RUIZ GIMENEZ ANA PAULA
DR. RUIZ MANINI LUCAS
DR. RUIZ SENDRA JUAN ANDRES
DR. RUSSO FEDERICO
DR. RUSSO GABRIEL
DR. RUSSO HUGO MAURICIO
DRA. SAAD GRECO NATALIA
DRA. SAAVEDRA SONIA
DR. SABA JAVIER ANDRES
DR. SAIT JUAN EDUARDO
DRA. SALAS IVANA
DRA. SALICA, CLAUDIA ALEJANDRA
DR. SALINAS EDUARDO ALBERTO
DRA. SALINAS FABIANA
DR. SALINAS JORGE
DR. SALVADORES EDUARDO DANIEL
DR. SÁNCHEZ FRANKLIN
DRA. SANCHEZ GABRIELA
DR. SANCHEZ GUSTAVO
DR. SANCHEZ JORGE ALBERTO
DRA. SANCHEZ MARIA ROSA
DR. SANCHEZ RICARDO
DR. SANDEZ LUJAN MARCELO ENRIQUE
DR. SANTORI MARINERO FEDERICO RAUL
DR. SANSO MAXIMILIANO
DRA. SANTANA MARIA DANIELA
DR. SANZ MARICEL
DR. SARDIÑA JUAN ANTONIO
DR. SARMIENTO LACIAR JUAN GABRIEL
DRA. SEGOVIA ROMINA
DRA. SENDRA DE RUIZ TERESA
DR. SHEJINA SHILOAM BORDON
DR. SILVA OSCAR GABRIEL
DR. SLAVUTZKY LEONARDO
DRA. SLAVUTZKY PAULINA
DRA. SOLERA ROMINA
DRA. SORIANO CRISTINA
DRA. SORIA GISELA YANIRA
DR. STEFAN ANDRADE PABLO NICOLAS
DR. STOLAROWA MARCELO
DR. STORAROWA MARCELO ALEJANDRO
DR. STUSEK RAMOS JORGE
DR. SUSSO GODOY MARTIN CRISTIAN
DR. TASCHERET SANTIAGO
DR. TEJADA JOSE DANIEL
DRA. TEJADA OLIVARES CARLA IVONNE
DR. TEJADA PEDROTTI MALCO
DRA. TEJADA SONIA
DR. TELLO MARTIN ADRIANA DEL VALLE
DR. TESTI MARCELO BRUNO
DR. TICLE BENITEZ FEDERICO HERNAN
DR. TORCIVIA MARTIN
DR. TORES FEDERICO EMANUEL
DR. TORRES CALVO OSCAR MAXIMILIANO
DR. TORRES JOSE OSCAR
DRA. TORRES MARIA DEL VALLE
DR. TROCHE ANDRES
DR. TURCUMAN MARTIN
DRA. ULIARTE LUIS MARIA
DR. UZAIR FARIAS NALLIB HUGO
DR. UZAIR MOHAMED NASSER
DR. VADILLO MAXIMILIANO
DR. VALENZUELA MARCELO
DR. VALLEJO PATRICIO LUIS
DR. VALLEJO PACHECO EMILIANO
DRA. VARGAS CLAUDIA
DR. VARGAS HIDALGO CARLOS ALFREDO
DRA. VARGAS CHIRINO ROMINA
DR. VARGAS JUAN MANUEL
DR. VARGAS LUCAS JAVIER
DR. VARGAS CARRERA HORACIO
DR. VAZQUEZ GUSTAVO
DRA. VAZQUEZ ROCIO
DR. VEGA OMAR
DRA. VELASQUEZ MARIA EUGENIA
DR. VERA CLAUDIO
DR. VIDELA CRISTIAN ARMANDO
DR. VIDELA JORGE
DR. VIDELA JOSE LUIS
DR. VIDELA MATIAS
DR. VILA CARLOS LEONARDO
DR. VILA GUSTAVO ERNESTO RAMON
DRA. VILDOZO MIRTHA
DR. VILLALBA JORGE OMAR
DR. VILLALBA LEONARDO
DR. VILLALOBOS EDUARDO
DR. VILLA GIMENEZ FEDERICO MANUEL
DR. VILLAFAÑE EDUARDO
DR. VILLAVERDE DANIEL
DR. VILLAVERDE PATRICIO DAMIAN
DR. VILLAVICENCIO DAMIAN
DR. VILLAVICENCIO GUILLERMO
DR. VILLEGAS JESUS MARIO
DR. VILLEGAS MAURO
DR. VOLPIANSKY JONATAN MAURICIO
DR. YANZON RICHARD WILLIAMS
DR. YAZZAR SAHID ANTONIO
DRA. YGONETT EMILIA ALEJANDRA
DR. YOSSA RICARDO
DR. YRIBARREN DELFOR
DR. ZALAZAR EDUARDO
DR. ZALLIO JUAN
DR. ZAPATA MARCONE JUAN MARCOS
DR. ZARATE NAHUEL
DR. ZOLLI ROJAS BRUNO FEDERICO
DR. ZULETA MARTIN ALBERTO
DR. ZUNINO GUSTAVO`

export function SignUpBlock () {
    const {addUser, addDesplegable, updateDesplegables, desplegables } = useContext(DataContext);
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [userType, setUserType] = useState('')
    const [error, setError] = useState('')

    const handleSubmit = async (event) => {
        event.preventDefault();
        try {
            const { result, error } = await signUp(email, password);
            setEmail('');
            setPassword('');
            setUserType('');
            setError(null);
            const data = {
                userId: result.uid,
                type: userType
            }
            await addUser(data)
        }catch (error) {
            setError(error.message);
            console.error('Error adding user:', error);
        }
      };
    const convertNames = () =>{
        console.log(listaDefensa.split(/\r?\n/)).array.forEach(element => {
            await addDesplegable('defensaParticular', `${newDefensa} - ${newDefensaTipo}`)
        });
    }

    return(
        <div>
        <h1>Add User</h1>
        {error && <p style={{ color: 'red' }}>{error}</p>}
        <form onSubmit={handleSubmit}>
            <label>
            Email:
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
            </label>
            <br />
            <label>
            Password:
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
            </label>
            <br />
            <label>
            User Type:
            <select value={userType} onChange={(e) => setUserType(e.target.value)}>
                <option value="">Select User Type</option>
                <option value="admin">Admin</option>
                <option value="uac">UAC</option>
                <option value="ugaadmin">UGA Admin</option>
                <option value="operador">operador</option>
                <option value="uapyt">UAPyT</option>
            </select>
            </label>
            <br />
            <button type="submit">Add User</button>
        </form>
        <button onClick={()=>(convertNames())}>GenerarPDF</button>
        </div>
    )
}