import { initializeApp } from "firebase/app";
import { getFirestore, doc, updateDoc } from "firebase/firestore";
import 'dotenv/config';

// Firebase configuration from .env
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Simplified list for testing and to avoid truncation issues
const professionalsList = [
    "Dra. María Filomena Noriega",
    "Dr. Alejandro Castan",
    "Dr. Horacio Merino",
    "Dr. Nicolás Gomez Camozzi",
    "Dr. Mario David Moran",
    "Dr. Gustavo De la Fuente",
    "Dr. Julián Gil",
    "Dr. Claudio Vera",
    "Dr. Leonardo Villalba",
    "Dr. Cesar Rolando Jofre",
    "Dr. Federico Petrignani",
    "Dr. Leonardo Slavutzky",
    "Dr. Fernando Bonomo",
    "Dr. Faustino Gelvez",
    "Dra. Maira Elias",
    "Dr. José Manuel Beltrán",
    "Dra. Sandra Lorena Leveque",
    "Dra. Carla Marcela Manini Cortez",
    "Dr. José Daniel Tejada",
    "Dr. Marcelo Antonio Abarca Gomez",
    "Dr. Manuel Gimenes Puchol",
    "Dr. Martin Alberto Zuleta",
    "Dr. Jorge Aguiar",
    "Dr. Carlos Fernández Torres",
    "Dra. Cecilia Bianchi",
    "Dr. Miguel Angel Gelvez Muñoz",
    "Dr. José Luis Guidet Montilla",
    "Dr. Roberto Jorge Montilla",
    "Dr. Miguel Antonio Rodriguez Muñoz",
    "Dra. Ivana Salas",
    "Dr. Carlos Leonardo Vila",
    "Dra. Viviana Belén",
    "Dr. Pablo Marcelo Pereyra",
    "Dr. Jorge Videla",
    "Dr. Juan Humberto Fonzalida",
    "Dra. Flavia Belén Funes",
    "Dr. Hernán Pascual",
    "Dr. Omar Néstor Quiroga Vargas",
    "Dra. Lidia Andrea Román Barón",
    "Dr. Agustín Idemi",
    "Dr. Leonardo Isaias Miranda",
    "Dr. Carlos Alberto Reinoso",
    "Dr. Benjamín Balmaceda",
    "Dra. Adriana Cabrera de Pandiella",
    "Dr. Fernando Echegaray",
    "Dr. Carlos Daniel Rivadeo",
    "Dr. Gustavo Ernesto Ramón Vila",
    "Dr. Fernando Bueno",
    "Dr. Guillermo Jesús Carrizo",
    "Dr. Gustavo Ariel González Aguilera",
    "Dr. Gustavo González",
    "Dr. Julio César Noguera",
    "Dr. Jorge Antonio Olivera Legleu",
    "Dr. Martin Torcivia",
    "Dr. Juan Javier Cámpora",
    "Dr. Nicolás Fiorentino",
    "Dr. Antonio Javier Jofre",
    "Dr. Ricardo David Lorenzo Mira",
    "Dr. Franco José Montes",
    "Dr. Juan Eduardo Sait",
    "Dra. Estefanía Pamela Alarcón Capdevila",
    "Dr. Reinaldo Luciano Bedini",
    "Dr. Matías Díaz López",
    "Dr. Maximiliano Marcos Paz",
    "Dr. Omar Quiroga",
    "Dr. Lucas Ruiz Manini",
    "Dra. Fabiana Salinas",
    "Dr. Federico Hernán Ticle Benítez",
    "Dr. Oscar Adarvez",
    "Dra. Ivana Mariela Ahumada",
    "Dr. Mario Ariel Bustos García",
    "Dr. Darío Caparros",
    "Dr. Luis Leonel García Alvarez",
    "Dr. Alejandro Genest",
    "Dr. Juan Carlos González",
    "Dr. Jorge Enrique Guillén Giménez",
    "Dr. José Luis Lavia Paez",
    "Dr. Joaquín Galdeano Moine",
    "Dra. Cintia Oki Bonanno",
    "Dr. Roberto Carlos Olivera",
    "Dra. Gemma Trinidad Orellano Gramajo",
    "Dr. Maximiliano Gustavo Orozco",
    "Dr. Pablo Marcelo Pereira Samper",
    "Dr. Juan Manuel Riveros",
    "Dr. Elio Roco Varela",
    "Dra. María del Valle Torres",
    "Dr. Mohamed Nasser Uzair",
    "Dr. José Luis Videla",
    "Dr. Rodrigo José Aguirre",
    "Dr. Darío Amaya",
    "Dr. Ricardo Aracena",
    "Dr. Marcial Eduardo Barrionuevo",
    "Dr. Rolando Berrido",
    "Dr. Andrés Bertagna",
    "Dr. José Nicolas Carrizo",
    "Dra. Patricia Alejandra Carrizo",
    "Dr. Fernando Chavez",
    "Dra. Mariana Antonela Coria",
    "Dr. Alejandro Carlos Davila",
    "Dr. Néstor Reinaldo Durán Hernández",
    "Dr. Fernando Elizondo",
    "Dr. Adrián Espejo",
    "Dr. Mario Gallo",
    "Dr. Diego Eduardo Gomez",
    "Dr. Ismael Antonio Hidalgo",
    "Dra. Ester Iragorre",
    "Dr. Juan Pablo Melián Navarro",
    "Dra. Paola Miers",
    "Dr. Alejandro Daniel Miquelarena Meritelo",
    "Dr. Andrés Alejandro Noguera",
    "Dr. Maximiliano Paez Delgado",
    "Dr. Gonzalo Palacios",
    "Dr. Enzo Penizzotto",
    "Dr. Sergio Pérez",
    "Dra. Olga Mariela Pérez",
    "Dra. Yamila Piozzi",
    "Dr. Héctor Ponce",
    "Dra. Valeria Aida Recabarren Zamarbide",
    "Dr. Carlos Roberto Reinoso",
    "Dr. Oscar Gabriel Silva",
    "Dra. Romina Solera",
    "Dra. Sonia Tejada",
    "Dra. María Eugenia Velásquez",
    "Dr. Juan Marcos Zapata Marcone",
    "Dra. Natalia Adarvez",
    "Dra. Sandra Viviana Alanis Sabag",
    "Dra. María Encarnación Burguez",
    "Dra. Brenda Caceres",
    "Dr. Horacio Nicolas Carrizo",
    "Dr. Jorge Castan",
    "Dr. Fernando Castro",
    "Dr. Sergio Andres Cortez",
    "Dra. Josela Echegaray Moya",
    "Dr. Ramiro Espinosa",
    "Dra. Emilce Forte",
    "Dr. Angel Humberto Ramón Furlotti",
    "Dr. Francisco Ricardo Furlotti",
    "Dra. Sofía Inés Gamboa Costa",
    "Dr. Guido Jordan Gangemi",
    "Dra. Silvia García Gutiérrez",
    "Dr. Santiago García",
    "Dr. Gastón Omar Garrido Balmaceda",
    "Dra. Yanina González",
    "Dra. Paola Ibañez",
    "Dr. Cristian Junes Navas",
    "Dr. Walter Alberto Lloveras",
    "Dr. Cristian Alejandro Marchesi",
    "Dr. Santiago Abel Mazzei Mattar",
    "Dra. María Elena Molina Jaime",
    "Dr. Federico Jesús Molinero",
    "Dr. Antonio Mora",
    "Dra. Vanina Muñoz",
    "Dra. María de los Ángeles Olivera Soler",
    "Dr. Néstor Emanuel Olivera",
    "Dra. Yanina Natalia Olmos Bustos",
    "Dr. Henri Peralta",
    "Dr. Mauricio Portell",
    "Dr. Renzo Quero",
    "Dr. Francisco Jesús Quiroga Bubica",
    "Dra. Laura Reus",
    "Dra. María Daniela Santana",
    "Dra. Cristina Soriano",
    "Dr. Marcelo Valenzuela",
    "Dr. Emiliano Vallejo Pacheco",
    "Dr. Horacio Vargas Carrera",
    "Dr. Damián Villavicencio",
    "Dr. Francisco José Agrello",
    "Dr. Julián Ernesto Aguiar",
    "Dra. Noelia del Carmen Aguilera",
    "Dr. Rodrigo Ale",
    "Dra. Cristina Arce Brozina",
    "Dra. Yesica Evelin Arias Villarroel",
    "Dr. Facundo Arroyo",
    "Dra. Ema Baigorria",
    "Dra. Alejandra Barbero Correa",
    "Dr. Miguel Angel Becerra",
    "Dr. Lucio Benavidez",
    "Dr. Arturo Bode",
    "Dr. Enzo Bonomo",
    "Dr. Raul Fernando Bustos Laspina",
    "Dra. María Leila Caballero Achem",
    "Dra. Julieta Campillay",
    "Dra. Sabrina Campillay",
    "Dr. Arnaldo Abel Cámpora Gutiérrez",
    "Dr. Guillermo Cano",
    "Dra. Laura Natalia Carrizo",
    "Dr. José Luis Castro",
    "Dr. Jorge Ignacio Conturso",
    "Dr. Jorge Andres Coria",
    "Dr. Roberto Luis Correa Esbry",
    "Dr. Ivan Culkaj",
    "Dr. Gabriel Antonio Damico Quintar",
    "Dra. María Vanesa De Dax Sanso",
    "Dra. Ana De la Torre",
    "Dr. Antonio De la Torre",
    "Dra. Marcela De la Vega",
    "Dr. José Maria De Vita",
    "Dra. Graciela Delgado",
    "Dra. Nadia Ludmila Derka",
    "Dra. Maria Micaela Echeverría Manrique",
    "Dr. Mauricio Fabian Escudero",
    "Dra. Paola Escudero",
    "Dr. Esteban Adrian Espejo Amarfil",
    "Dr. Fabricio Fachinetti",
    "Dra. Silvia Mabel Falcón",
    "Dra. Estefanía Fernández",
    "Dr. Hipólito Fernández",
    "Dr. Marcelo Fernández",
    "Dr. Cristian Ariel Ferré",
    "Dra. Claudia Noemí Flores",
    "Dra. Yanina Paola Flores",
    "Dr. Luis Federico Galvarini",
    "Dr. Milenko García",
    "Dr. Agustín Gatica",
    "Dra. Carolina Gianinetto",
    "Dr. Gastón Alberto Gil",
    "Dr. Duilio Gomez",
    "Dr. Edgardo Gomez",
    "Dra. Jesica Lorena Gomez Jofre",
    "Dra. Mónica González",
    "Dr. Nicolás Ernesto González",
    "Dra. Liliana Guardia",
    "Dr. Arsenio Demetrio Gyordan Rosa",
    "Dra. Sandra Gutiérrez",
    "Dra. María Guadalupe Guzmán",
    "Dra. Patricia Andrea Guzmán Vega",
    "Dra. Estefanía Natalia Heredia",
    "Dr. José Manuel Herrero Palacios",
    "Dr. Amin Lucas Herman",
    "Dra. Ana Paula Ibañez",
    "Dra. María Guadalupe Illanes",
    "Dr. Daniel Jaime Ovalles",
    "Dra. Valeria Jorquera",
    "Dra. Lola Fabiana Leites",
    "Dra. Gabriela Leites Maldonado",
    "Dr. Raul Reinaldo Llorca",
    "Dr. Ruben Eduardo Lloveras Parra",
    "Dr. Franco Marchese",
    "Dr. Juan Manuel Marinaro",
    "Dr. Gustavo Fabián Clavel Martin",
    "Dr. Humberto Martinez Oro",
    "Dr. Matías Massa",
    "Dr. Rodrigo Daniel Metola San Nicolás",
    "Dra. Ana Carolina Meyer Espin",
    "Dr. Maximiliano Andres Miranda",
    "Dr. Fernando Molina Perzi",
    "Dr. Carlos Cesar Moncunill",
    "Dr. Rolando Lorenzo Montaño",
    "Dra. Maria Victoria Montes Bustos",
    "Dr. Germán Antonio Montiveros Palacio",
    "Dra. Romina Montiveros",
    "Dr. Fernando Moreira",
    "Dr. Maximiliano Andres Muñoz Cabral",
    "Dr. Pablo Nacussi",
    "Dra. Soledad Nicolia",
    "Dra. Laura Nuñez",
    "Dr. Fabian Rodolfo Olivera Sanchez",
    "Dr. Arnaldo Daniel Ottolia Caputo",
    "Dr. Andres Mauricio Pacheco",
    "Dr. Mario Javier Padilla Ruz",
    "Dra. Jesica Paez",
    "Dr. Sebastián Peluc Pérez",
    "Dr. Leonardo Raul Perzi",
    "Dra. Patricia Poblete",
    "Dr. Ruben Alfredo Pontoriero",
    "Dr. Sebastian Pontoriero",
    "Dr. Emiliano Angel Prado Garcia",
    "Dra. Maria Agustina Putelli Delgado",
    "Dra. Elena Beatriz Quiroga de Zalazar",
    "Dra. Silvina Ricchini",
    "Dr. José Alejandro Rivero",
    "Dr. Claudio Rodriguez",
    "Dr. Aníbal Rojas",
    "Dr. Gonzalo Martin Rojas",
    "Dr. Ivan Roman",
    "Dr. Daniel Romero",
    "Dr. Carlos Andres Rueda",
    "Dra. Ana Paula Ruiz Gimenez",
    "Dr. Federico Russo",
    "Dra. Natalia Saad Greco",
    "Dr. Eduardo Alberto Salinas",
    "Dra. Maria Rosa Sanchez",
    "Dr. Federico Raul Santori Marinero",
    "Dra. Maricel Sanz",
    "Dr. Juan Gabriel Sarmiento Laciar",
    "Dra. Teresa Sendra de Ruiz",
    "Dr. Federico Emanuel Tores",
    "Dr. Oscar Maximiliano Torres Calvo",
    "Dr. Andres Troche",
    "Dr. Nallib Hugo Uzair Farias",
    "Dr. Patricio Luis Vallejo",
    "Dra. Claudia Vargas",
    "Dra. Romina Vargas Chirino",
    "Dra. Mirtha Vildozo",
    "Dr. Eduardo Villafañe",
    "Dr. Jonatan Mauricio Volpiansky",
    "Dr. Delfor Yribarren",
    "Dr. Gustavo Zunino"
];

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const updateList = async () => {
    try {
        console.log(`Preparing to replace defensaParticular with ${professionalsList.length} items...`);
        const docRef = doc(db, "desplegables", "desplegables");
        await updateDoc(docRef, {
            defensaParticular: professionalsList
        });
        console.log("Successfully replaced defensaParticular list!");
        process.exit(0);
    } catch (e) {
        console.error("Error updating document: ", e);
        process.exit(1);
    }
};

updateList();
